// If you are unfamiliar with Style Dictionary take a look at the docs:
// https://styledictionary.com
const StyleDictionary = require('style-dictionary');

// This is a custom name transform for Style Dictionary
// It will take the token's object path and create a dot-separated string
// for example: activityBar.background
StyleDictionary.registerTransform({
  name: 'vsCodeName',
  type: 'name',
  transformer: (token) => {
    // 
    if (token.path[0] === 'tokenColors') {
      // This allows you to have tokens at multiple levels
      // like `comment` and `comment.line`
      if (token.name === '*') {
        // removes the first and last parts of the path
        return token.path.slice(1,-1).join('.')
      } else {
        // removes the first part of the path which would be 'tokenColors'
        return token.path.slice(1).join('.')
      }
    } else {
      // Used for application colors
      return token.path.join('.');
    }
  }
});

// Add a custom format that will generate the VSCode theme JSON
StyleDictionary.registerFormat({
  name: 'vsCodeTheme',
  formatter: (dictionary, config) => {
    // VSCode theme JSON files have this structure
    const theme = {
      "name": `Nu Disco ${config.themeType}`,
      "type": config.themeType,
      "colors": {},
    }
    
    // Filter out the design tokens we don't want to add to the
    // 'colors' object. This includes core colors defined in tokens/core.json5
    // and tokenColors defined in theme/tokenColors
    dictionary.allProperties.filter((token) => {
      return !['color','tokenColors'].includes(token.path[0])
    }).forEach((token) => {
      // Add each token to the colors object, the name is generated by the custom
      // transform defined below
      theme.colors[token.name] = token.value;
    });
    
    // Map the tokenColors
    theme.tokenColors = dictionary.allProperties.filter((token) => {
      return token.path[0] === 'tokenColors'
    }).map((token) => ({
      scope: token.name,
      settings: {
        foreground: token.value,
        fontStyle: token.fontStyle,
      }
    }));
    
    // Style Dictionary formats expect a string that will be then written to a file
    return JSON.stringify(theme, null, 2);
  }
});

const themeTypes = [`dark`, `light`];

// Iterate over each theme type and build with style dictionary
// We will use the theme type to include design tokens from that theme
// and also use it to create separate vs code theme files
themeTypes.forEach((themeType) => {
  StyleDictionary.extend({
    // Style Dictionary will find all files defined in source and do a deep merge
    // on them. 
    source: [
      // This is the core color palette
      `tokens/core.json5`,
      // These directories are where we keep theme specific tokens
      `tokens/${themeType}/*.json5`,
      // These are like component tokens, they reference theme type tokens
      `tokens/application/*.json5`,
      `tokens/syntax/*.json5`
    ],
    platforms: {
      vscode: {
        // Directory to build files to
        buildPath: `build/`,
        // Adding a custom attribute on the platform so we can use it in
        // the custom format
        themeType: themeType,
        // The name of the custom transforms we defined above
        transforms: [`vsCodeName`],
        files: [{
          // The path the file will be created at. Make sure this matches
          // the file paths defined in the package.json
          destination: `nu-disco-${themeType}.color-theme.json`,
          // The name of the custom format defined above
          format: `vsCodeTheme`
        }]
      }
    }
  }).buildAllPlatforms();
});